routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

  



Route::group(['middleware' => ['forceSsl', 'web']], function () {
// Authentication Routes...

Route::get('/', 'HomeController@index');


Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
//$this->get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
//$this->post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');

// Email Verification Routes...
//$this->get('email/verify', 'Auth\VerificationController@show')->name('verification.notice');
//$this->get('email/verify/{id}', 'Auth\VerificationController@verify')->name('verification.verify');
//$this->get('email/resend', 'Auth\VerificationController@resend')->name('verification.resend');


});


Route::group(['middleware' => ['forceSsl', 'auth']], function () {

Route::get('/home', 'HomeController@index');

Route::get('generator_builder', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@builder');

Route::get('field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@fieldTemplate');

Route::get('relation_field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@relationFieldTemplate');

Route::post('generator_builder/generate', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generate');

Route::post('generator_builder/rollback', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@rollback');

Route::post(
    'generator_builder/generate-from-file',
    '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generateFromFile'
);

Route::resource('inventories', 'InventoryController');
Route::resource('invento', 'SyncProductIdsController');

Route::resource('users', 'UserController');
Route::resource('roles', 'RoleController');
Route::resource('permissions', 'PermissionController');
Route::resource('requisitionForms', 'RequisitionFormController');

});

Route::group(['middleware' => ['forceSsl']], function () {
  
    
Route::webhooks('woo-inveto-stock-manager', 'woo-webhook');
Route::webhooks('square-inveto-stock-manager', 'square-webhook');



});
    

app/Http/Controllers/RequisitionFormController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\RequisitionFormDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateRequisitionFormRequest;
use App\Http\Requests\UpdateRequisitionFormRequest;
use App\Repositories\RequisitionFormRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use Response;
use Auth;
use Carbon\Carbon; 
use Mail;
use App\Mail\OnlineRequisitionRequest;
use App\User;

class RequisitionFormController extends AppBaseController
{
    /** @var  RequisitionFormRepository */
    private $requisitionFormRepository;

    public function __construct(RequisitionFormRepository $requisitionFormRepo)
    {
        $this->requisitionFormRepository = $requisitionFormRepo;
        $this->middleware(['auth', 'role:Admin', 'clearance'])->except('create', 'store');
    }

    /**
     * Display a listing of the RequisitionForm.
     *
     * @param RequisitionFormDataTable $requisitionFormDataTable
     * @return Response
     */
    public function index(RequisitionFormDataTable $requisitionFormDataTable)
    {
        return $requisitionFormDataTable->render('requisition_forms.index');
    }

    /**
     * Show the form for creating a new RequisitionForm.
     *
     * @return Response
     */
    public function create()
    {
        return view('requisition_forms.create')->with('user',  Auth::User());
    }

    /**
     * Store a newly created RequisitionForm in storage.
     *
     * @param CreateRequisitionFormRequest $request
     *
     * @return Response
     */
    public function store(CreateRequisitionFormRequest $request)
    {
        $input = $request->all();

        $requisitionForm = $this->requisitionFormRepository->create($input);

        if(!Auth::User()->hasRole('Admin')){

            Flash::success('Requisition Form saved successfully.');

            return redirect(route('requisitionForms.create'));

        }

        Flash::success('Requisition Form saved successfully.');

        return redirect(route('requisitionForms.index'));

    }

    /**
     * Display the specified RequisitionForm.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $requisitionForm = $this->requisitionFormRepository->find($id);

        if (empty($requisitionForm)) {
            Flash::error('Requisition Form not found');

            return redirect(route('requisitionForms.index'));
        }

        return view('requisition_forms.show')->with('requisitionForm', $requisitionForm);
    }

    /**
     * Show the form for editing the specified RequisitionForm.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $requisitionForm = $this->requisitionFormRepository->find($id);
        $dateNeeded = new Carbon($requisitionForm->date_needed);
        $requisitionForm->date_needed = $dateNeeded->format('Y-m-d');

        $user = User::findOrFail($requisitionForm->user_id);

        if (empty($requisitionForm)) {
            Flash::error('Requisition Form not found');

            return redirect(route('requisitionForms.index'));
        }

        return view('requisition_forms.edit')->with(['requisitionForm' => $requisitionForm, 'user' => $user]);
    }

    /**
     * Update the specified RequisitionForm in storage.
     *
     * @param  int              $id
     * @param UpdateRequisitionFormRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateRequisitionFormRequest $request)
    {
        $requisitionForm = $this->requisitionFormRepository->find($id);
        $user = User::findOrFail($requisitionForm->user_id);
        
        if (empty($requisitionForm)) {
            Flash::error('Requisition Form not found');
            return redirect(route('requisitionForms.index'));
        }

        $requisitionForm = $this->requisitionFormRepository->update($request->all(), $id);

        if($requisitionForm->status != 'Approved'){
            $this->emailStatus($requisitionForm);
        }
    
        Flash::success('Requisition Form updated successfully.');

        return redirect(route('requisitionForms.index'));
    }

    /**
     * Remove the specified RequisitionForm from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $requisitionForm = $this->requisitionFormRepository->find($id);

        if (empty($requisitionForm)) {
            Flash::error('Requisition Form not found');

            return redirect(route('requisitionForms.index'));
        }

        $this->requisitionFormRepository->delete($id);

        Flash::success('Requisition Form deleted successfully.');

        return redirect(route('requisitionForms.index'));
    }

    private function emailStatus($requisitionForm){

        $user = User::findOrFail($requisitionForm->user_id);

        if($user){

            $data = [
                "email" => $user->email,
                "username" => $user->name,
            ]; 
    
            if($requisitionForm === 'Approved'){
                Mail::to($data['email'])->send(new OnlineRequisitionRequest($data));
    
            }elseif($status === 'Denied'){
    
    
            }else{
    
    
            }

        }

    }
}

resources/views/requisition_forms/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Requisition Form
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'requisitionForms.store']) !!}

                        @include('requisition_forms.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/requisition_forms/datatables_actions.blade.php
{!! Form::open(['route' => ['requisitionForms.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('requisitionForms.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-edit"> Edit</i>
    </a>
    {!! Form::button('<i class="glyphicon glyphicon-trash"> Delete</i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/requisition_forms/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Requisition Form
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($requisitionForm, ['route' => ['requisitionForms.update', $requisitionForm->id], 'method' => 'patch']) !!}

                        @include('requisition_forms.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/requisition_forms/fields.blade.php
<!-- hidden user id field -->

{!! Form::number('user_id', $user['id'], ['class' => 'hidden form-control']) !!}
{!! Form::text('user_name', $user['name'], ['class' => 'hidden form-control']) !!}

<!-- Purpose Field -->
<div class="form-group col-sm-12 col-lg-12">
        {!! Form::label('item_required', 'Item Required:') !!}
        {!! Form::textarea('item_required', null, ['class' => 'form-control', 'required' => 'required']) !!}
    </div>

<!-- Date Needed Field -->
<div class="form-group col-sm-6">
    {!! Form::label('date_needed', 'Date Needed:') !!}
    {!! Form::date('date_needed', null, ['class' => 'form-control','id'=>'date_needed', 'required' => 'required']) !!}
</div>

@section('scripts')
    <script type="text/javascript">
        $('#date_needed').datetimepicker({
            format: 'YYYY-MM-DD',
            useCurrent: false
        })
    </script>
@endsection

<!-- Department Field -->
<div class="form-group col-sm-6">
    {!! Form::label('department', 'Department:') !!}
    {!! Form::select('department', ['The Planning Handbook' => 'The Planning Handbook', 'The Travelling Wine Merchant' => 'The Travelling Wine Merchant', 'The New Wine Company' => 'The New Wine Company', 'SEO' => 'SEO', 'Websites' => 'Websites', 'Andrew House / Company-wide' => 'Andrew House / Company-wide'], null, ['class' => 'form-control', 'required' => 'required']) !!}
</div>

<!-- Purpose Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('purpose', 'Purpose of Purchase:') !!}
    {!! Form::textarea('purpose', null, ['class' => 'form-control', 'required' => 'required']) !!}
</div>

<!-- Vendor Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('vendor_name', 'Vendor Name:') !!}
    {!! Form::text('vendor_name', null, ['class' => 'form-control', 'required' => 'required']) !!}
</div>

<!-- Vendor Web Address Field -->
<div class="form-group col-sm-6">
    {!! Form::label('vendor_web_address', 'Vendor Web Address:') !!}
    {!! Form::text('vendor_web_address', null, ['class' => 'form-control', 'required' => 'required']) !!}
</div>

<!-- Product Code Field -->
<div class="form-group col-sm-6">
    {!! Form::label('product_code', 'Product Code:') !!}
    {!! Form::text('product_code', null, ['class' => 'form-control', 'required' => 'required']) !!}
</div>

<!-- Unit Price Field -->
<div class="form-group col-sm-6">
    {!! Form::label('unit_price', 'Unit Price (Net of VAT)(£):') !!}
    {!! Form::number('unit_price', null, ['class' => 'form-control', 'required' => 'required', 'step' => '0.01']) !!}
</div>

<?php $user = Auth::user() ?>

@if($user->hasRole('Admin')) 
<?php $cols = 'col-sm-4'; ?>
@else
<?php $cols = 'col-sm-6'; ?>
@endif

<!-- Qty Field -->
<div class="form-group <?php echo $cols; ?>">
    {!! Form::label('qty', 'Qty:') !!}
    {!! Form::number('qty', null, ['class' => 'form-control', 'required' => 'required']) !!}
</div>

<!-- Payments Field -->
<div class="form-group <?php echo $cols; ?>">
    {!! Form::label('payments', 'Payments:') !!}
    {!! Form::select('payments', ['One-Off Payment' => 'One-Off Payment', 'Monthly Payment' => 'Monthly Payment'], null, ['class' => 'form-control', 'required' => 'required']) !!}
</div>

@if($user->hasRole('Admin')) 
<!-- Payments Field -->
<div class="form-group <?php echo $cols; ?>">
    {!! Form::label('status', 'Status:') !!}
    {!! Form::select('status', ['Waiting' => 'Waiting', 'Approved' => 'Approved', 'Denied' => 'Denied'], null, ['class' => 'form-control', 'required' => 'required']) !!}
</div>
@endif

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
   <!-- <a href="{!! route('requisitionForms.create') !!}" class="btn btn-default">Cancel</a> -->
</div>

resources/views/requisition_forms/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Requisition Forms</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('requisitionForms.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('requisition_forms.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/requisition_forms/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Requisition Form
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('requisition_forms.show_fields')
                    <a href="{!! route('requisitionForms.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/requisition_forms/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $requisitionForm->id !!}</p>
</div>

<!-- User Id Field -->
<div class="form-group">
    {!! Form::label('user_id', 'User Id:') !!}
    <p>{!! $requisitionForm->user_id !!}</p>
</div>

<!-- Date Needed Field -->
<div class="form-group">
    {!! Form::label('date_needed', 'Date Needed:') !!}
    <p>{!! $requisitionForm->date_needed !!}</p>
</div>

<!-- Department Field -->
<div class="form-group">
    {!! Form::label('department', 'Department:') !!}
    <p>{!! $requisitionForm->department !!}</p>
</div>

<!-- Purpose Field -->
<div class="form-group">
    {!! Form::label('purpose', 'Purpose:') !!}
    <p>{!! $requisitionForm->purpose !!}</p>
</div>

<!-- Vendor Name Field -->
<div class="form-group">
    {!! Form::label('vendor_name', 'Vendor Name:') !!}
    <p>{!! $requisitionForm->vendor_name !!}</p>
</div>

<!-- Vendor Web Address Field -->
<div class="form-group">
    {!! Form::label('vendor_web_address', 'Vendor Web Address:') !!}
    <p>{!! $requisitionForm->vendor_web_address !!}</p>
</div>

<!-- Product Code Field -->
<div class="form-group">
    {!! Form::label('product_code', 'Product Code:') !!}
    <p>{!! $requisitionForm->product_code !!}</p>
</div>

<!-- Unit Price Field -->
<div class="form-group">
    {!! Form::label('unit_price', 'Unit Price:') !!}
    <p>{!! $requisitionForm->unit_price !!}</p>
</div>

<!-- Qty Field -->
<div class="form-group">
    {!! Form::label('qty', 'Qty:') !!}
    <p>{!! $requisitionForm->qty !!}</p>
</div>

<!-- Payments Field -->
<div class="form-group">
    {!! Form::label('payments', 'Payments:') !!}
    <p>{!! $requisitionForm->payments !!}</p>
</div>

resources/views/requisition_forms/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}

@section('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endsection